# Generated by Django 3.2.16 on 2022-10-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeAnswers',
            fields=[
                ('id', models.SmallIntegerField(db_column='InsureeChoiceId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblInsureeAnswers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.SmallIntegerField(db_column='OptionID', primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, db_column='Options', max_length=200, null=True)),
                ('option_value', models.IntegerField(blank=True, db_column='OptionMark', default=0, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblOptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.SmallIntegerField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, db_column='Question', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblQuestions',
                'managed': False,
            },
        ),
    ]
