# Generated by Django 3.2.17 on 2023-05-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, db_column='Question', max_length=400, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=400, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('Text', 'Text'), ('Checkbox', 'Checkbox'), ('Radio', 'Radio'), ('Dropdown', 'Dropdown')], db_column='QuestionType', default='1', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tblQuestions',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='insuree',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(db_column='OptionID', primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, db_column='Options', max_length=200, null=True)),
                ('option_value', models.IntegerField(blank=True, db_column='OptionMark', default=0, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=200, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('question_id', models.ForeignKey(db_column='Question', on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question')),
            ],
            options={
                'db_table': 'tblOptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsureeAnswer',
            fields=[
                ('id', models.AutoField(db_column='InsureeChoiceId', primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
                ('insuree_answer', models.ForeignKey(blank=True, db_column='OptionScore', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.option')),
                ('insuree_id', models.ForeignKey(blank=True, db_column='Insuree', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
                ('question', models.ForeignKey(blank=True, db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question')),
            ],
            options={
                'db_table': 'tblInsureeAnswers',
                'managed': True,
            },
        ),
    ]
