# Generated by Django 3.2.17 on 2023-05-09 17:45

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0014_auto_20230509_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='score',
            field=models.IntegerField(blank=True, db_column='Score', null=True, default=0),
        )
    ]
