# Generated by Django 3.2.16 on 2022-11-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_auto_20221027_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insureeanswer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
    ]
