# Generated by Django 3.2.17 on 2023-05-10 10:55

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import insuree.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_auto_20230509_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureeanswer',
            name='insuree_answer',
            field=models.IntegerField(blank=True, db_column='Answer', null=True),
        ),
    ]
