# Generated by Django 3.2.16 on 2023-01-10 16:13

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20221111_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeanswer',
            name='answer_date',
            field=core.fields.DateField(blank=True, db_column='AnswerDate', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='audit_user_id',
            field=models.IntegerField(blank=True, db_column='AuditUserID', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_answer',
            field=models.ForeignKey(blank=True, db_column='Score', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.option'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.ForeignKey(blank=True, db_column='Insuree', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='officer_id',
            field=models.IntegerField(blank=True, db_column='OfficerID', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='question',
            field=models.ForeignKey(blank=True, db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
        ),
        migrations.AddField(
            model_name='option',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
    ]
