# Generated by Django 3.2.16 on 2022-12-15 16:11

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20221111_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_answer',
            field=models.ForeignKey(blank=True, db_column='OptionScore', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.option'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.ForeignKey(blank=True, db_column='Insuree', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='question',
            field=models.ForeignKey(blank=True, db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(db_column='Question', default=builtins.id, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Checkbox'), ('3', 'Radio'), ('4', 'Dropdown')], db_column='QuestionType', default='1', max_length=100, null=True),
        ),
    ]
