# Generated by Django 3.2.16 on 2022-11-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20221111_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_answer',
            field=models.ForeignKey(blank=True, db_column='Score', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.option'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.ForeignKey(blank=True, db_column='Insuree', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='question',
            field=models.ForeignKey(blank=True, db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='total_score',
            field=models.IntegerField(blank=True, db_column='InsureeScore', default=0, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(blank=True, db_column='Question', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.question'),
        ),
        migrations.AddField(
            model_name='option',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
    ]
