# Generated by Django 3.2.16 on 2022-11-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20221114_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree'),
        ),
    ]
