# Generated by Django 3.2.16 on 2023-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20221215_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Text', 'Text'), ('Checkbox', 'Checkbox'), ('Radio', 'Radio'), ('Dropdown', 'Dropdown')], db_column='QuestionType', default='1', max_length=100, null=True),
        ),
    ]
