# Generated by Django 3.2.16 on 2023-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_auto_20230110_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insureeanswer',
            old_name='insuree_answer',
            new_name='answer_score',
        ),
        migrations.AlterField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.IntegerField(blank=True, db_column='Insuree', null=True),
        ),
    ]
