# Generated by Django 3.2.25 on 2024-08-13 14:06

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_auto_20240202_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryInsuree',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.AutoField(db_column='TemporaryInsureeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='TemporaryInsureeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=12, null=True)),
                ('temporaryMPI', models.CharField(blank=True, db_column='TemporaryMPI', max_length=36, null=True)),
                ('audituser_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblTemporaryInsuree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TemporaryInsureeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'insuree_TemporaryInsureeMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.AddField(
            model_name='temporaryinsureemutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='temporaryinsureemutation',
            name='temporaryInsuree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree.temporaryinsuree'),
        ),
        migrations.AddIndex(
            model_name='temporaryinsuree',
            index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to', 'chf_id'], name='tblTemporar_LegacyI_dc7548_idx'),
        ),
    ]
