# Generated by Django 3.2.25 on 2024-06-12 12:08

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_remove_healthfacility_row_id'),
        ('core', '0016_add_last_login_on_interactive_user'),
        ('insuree', '0018_auto_20240202_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryInsureePolicy',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='InsureePolicyID', primary_key=True, serialize=False)),
                ('enrollment_date', core.fields.DateField(blank=True, db_column='EnrollmentDate', null=True)),
                ('start_date', core.fields.DateField(blank=True, db_column='StartDate', null=True)),
                ('effective_date', core.fields.DateField(blank=True, db_column='EffectiveDate', null=True)),
                ('expiry_date', core.fields.DateField(blank=True, db_column='ExpiryDate', null=True)),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblTemporaryInsureePolicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryInsuree',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('id', models.AutoField(db_column='TemporaryInsureeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='TemporaryInsureeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(blank=True, db_column='CHFID', max_length=12, null=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('other_names', models.CharField(db_column='OtherNames', max_length=100)),
                ('dob', core.fields.DateField(db_column='DOB')),
                ('dead', models.BooleanField(blank=True, db_column='Dead', default=False, null=True)),
                ('dod', core.fields.DateField(db_column='DOD', null=True)),
                ('deathReason', models.CharField(db_column='DeathReason', max_length=500, null=True)),
                ('head', models.BooleanField(db_column='IsHead')),
                ('marital', models.CharField(blank=True, db_column='Marital', max_length=1, null=True)),
                ('passport', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, db_column='CurrentAddress', max_length=200, null=True)),
                ('geolocation', models.CharField(blank=True, db_column='GeoLocation', max_length=250, null=True)),
                ('photo_date', core.fields.DateField(blank=True, db_column='PhotoDate', null=True)),
                ('card_issued', models.BooleanField(db_column='CardIssued')),
                ('offline', models.BooleanField(blank=True, db_column='isOffline', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblTemporaryInsuree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TemporaryInsureeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'insuree_TemporaryInsureeMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.RemoveIndex(
            model_name='family',
            name='tblFamilies_LegacyI_5129e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='insuree',
            name='tblInsuree_LegacyI_a4548b_idx',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='audituser_id',
            new_name='audit_user_id',
        ),
        migrations.RemoveField(
            model_name='insuree',
            name='row_id',
        ),
        # migrations.AddField(
        #     model_name='family',
        #     name='confirmation_type',
        #     field=models.ForeignKey(blank=True, db_column='ConfirmationType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='insuree.confirmationtype'),
        # ),
        # migrations.AddField(
        #     model_name='family',
        #     name='family_type',
        #     field=models.ForeignKey(blank=True, db_column='FamilyType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='families', to='insuree.familytype'),
        # ),
        # migrations.AddField(
        #     model_name='family',
        #     name='head_insuree',
        #     field=models.OneToOneField(db_column='InsureeID', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_of', to='insuree.insuree'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='family',
        #     name='json_ext',
        #     field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        # ),
        # migrations.AddField(
        #     model_name='family',
        #     name='location',
        #     field=models.ForeignKey(blank=True, db_column='LocationId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        # ),
        # migrations.AddField(
        #     model_name='family',
        #     name='uuid',
        #     field=models.CharField(db_column='FamilyUUID', default=uuid.uuid4, max_length=36, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='education',
        #     field=models.ForeignKey(blank=True, db_column='Education', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.education'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='family',
        #     field=models.ForeignKey(blank=True, db_column='FamilyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='insuree.family'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='gender',
        #     field=models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.gender'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='health_facility',
        #     field=models.ForeignKey(blank=True, db_column='HFID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='location.healthfacility'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='json_ext',
        #     field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='photo',
        #     field=models.OneToOneField(blank=True, db_column='PhotoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insuree.insureephoto'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='profession',
        #     field=models.ForeignKey(blank=True, db_column='Profession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.profession'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='relationship',
        #     field=models.ForeignKey(blank=True, db_column='Relationship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurees', to='insuree.relation'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='type_of_id',
        #     field=models.ForeignKey(blank=True, db_column='TypeOfId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.identificationtype'),
        # ),
        # migrations.AddField(
        #     model_name='insuree',
        #     name='uuid',
        #     field=models.CharField(db_column='InsureeUUID', default=uuid.uuid4, max_length=36, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='family',
        #     name='validity_from',
        #     field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        # ),
        # migrations.AlterField(
        #     model_name='insuree',
        #     name='current_village',
        #     field=models.ForeignKey(blank=True, db_column='CurrentVillage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        # ),
        # migrations.AlterField(
        #     model_name='insuree',
        #     name='validity_from',
        #     field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        # ),
        # migrations.AddIndex(
        #     model_name='family',
        #     index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to'], name='tblFamilies_LegacyI_79a19e_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='insuree',
        #     index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to', 'chf_id'], name='tblInsuree_LegacyI_6f5da6_idx'),
        # ),
        migrations.AddField(
            model_name='temporaryinsureemutation',
            name='insuree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree.temporaryinsuree'),
        ),
        migrations.AddField(
            model_name='temporaryinsureemutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='current_village',
            field=models.ForeignKey(blank=True, db_column='CurrentVillage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='education',
            field=models.ForeignKey(blank=True, db_column='Education', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='insuree.education'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='family',
            field=models.ForeignKey(blank=True, db_column='FamilyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryMembers', to='insuree.family'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='insuree.gender'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='health_facility',
            field=models.ForeignKey(blank=True, db_column='HFID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='photo',
            field=models.OneToOneField(blank=True, db_column='PhotoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='insuree.insureephoto'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='profession',
            field=models.ForeignKey(blank=True, db_column='Profession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='insuree.profession'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='relationship',
            field=models.ForeignKey(blank=True, db_column='Relationship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporaryInsurees', to='insuree.relation'),
        ),
        migrations.AddField(
            model_name='temporaryinsuree',
            name='type_of_id',
            field=models.ForeignKey(blank=True, db_column='TypeOfId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.identificationtype'),
        ),
        migrations.AddIndex(
            model_name='temporaryinsuree',
            index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to', 'chf_id'], name='tblTemporar_LegacyI_dc7548_idx'),
        ),
    ]
