# Generated by Django 3.2.16 on 2022-12-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_alter_insureeanswer_insuree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insureeanswer',
            name='total_score',
        ),
    ]
