# Generated by Django 3.2.16 on 2023-01-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_auto_20230111_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureeanswer',
            name='insuree_id',
            field=models.ForeignKey(db_column='Insuree', on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_answers', to='insuree.insuree'),
        ),
    ]
