# Generated by Django 3.2.16 on 2023-01-05 14:59

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0019_remove_insureeanswer_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeanswer',
            name='answer_date',
            field=core.fields.DateField(blank=True, db_column='AnswerDate', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='audit_user_id',
            field=models.IntegerField(blank=True, db_column='AuditUserID', null=True),
        ),
        migrations.AddField(
            model_name='insureeanswer',
            name='officer_id',
            field=models.IntegerField(blank=True, db_column='OfficerID', null=True),
        ),
    ]
