# Generated by Django 3.2.23 on 2024-02-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_auto_20240202_1607'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insuree',
            index=models.Index(fields=['legacy_id', 'validity_from', 'validity_to', 'chf_id'], name='tblInsuree_LegacyI_6f5da6_idx'),
        ),
    ]